name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: 'Build'
      run: make borealis NAME="borealis-linux"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: borealis-linux
        path: borealis-linux
        retention-days: 30
