name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make borealis NAME="borealis-linux"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: borealis-linux
        path: borealis-linux
        retention-days: 30

    - name: Upload artifact to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: borealis-linux
        asset_name: borealis-linux
        tag: ${{ github.ref }}
        overwrite: true

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'Build'
      run: make borealis NAME="borealis-mac"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: borealis-mac
        path: borealis-mac
        retention-days: 30
